# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='First Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=25, verbose_name='Sex')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('status', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=25, verbose_name='Marital Status')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('children', models.IntegerField(verbose_name='Children')),
                ('occupation', models.CharField(max_length=255, verbose_name='Occupation')),
                ('consultation_reason', models.TextField(blank=True, null=True, verbose_name='Reason for consultation')),
                ('familial_overweight', models.BooleanField(verbose_name='Familial Overweight')),
                ('flatmates', models.CharField(choices=[('L', 'Alone'), ('C', 'With Couple'), ('F', 'With Family')], max_length=25, verbose_name='Flatmates')),
                ('n_meals', models.PositiveSmallIntegerField(verbose_name='Number of daily meals')),
                ('snacks', models.BooleanField(verbose_name='Has snacks between meals')),
                ('eats_where', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('S', 'Street'), ('F', 'Family'), ('O', 'Other')], max_length=25, verbose_name='Where has meals')),
                ('eats_with', models.CharField(choices=[('L', 'Alone'), ('I', 'In Company')], max_length=25, verbose_name='With whom has meals')),
                ('eats_fast', models.BooleanField(verbose_name='Eats Fast')),
                ('who_buys', models.CharField(choices=[('P', 'Patient'), ('O', 'Other')], max_length=25, verbose_name='Who buys food')),
                ('who_cooks', models.CharField(choices=[('P', 'Patient'), ('O', 'Other')], max_length=25, verbose_name='Who cooks food')),
                ('preferences', models.CharField(max_length=255, verbose_name='Preferences')),
                ('aversions', models.CharField(max_length=255, verbose_name='Aversions')),
                ('overweight', models.BooleanField(verbose_name='Overweight')),
                ('icm', models.FloatField(verbose_name='ICM')),
                ('smokes', models.PositiveSmallIntegerField(verbose_name='Number of daily cigarettes')),
                ('drinks', models.CharField(max_length=255, verbose_name='Alcohol consumption')),
                ('sedentarism', models.BooleanField(verbose_name='Sedentarian')),
                ('hta', models.BooleanField(verbose_name='HTA')),
                ('hta_treatment', models.BooleanField(verbose_name='HTA Treatement')),
                ('cholesterol', models.BooleanField(verbose_name='Cholesterol')),
                ('cholesterol_treatment', models.BooleanField(verbose_name='Cholesterol Treatment')),
                ('hdl', models.PositiveSmallIntegerField(verbose_name='Cholesterol HDL')),
                ('ldl', models.PositiveSmallIntegerField(verbose_name='Cholesterol LDL')),
                ('cholesterol_total', models.PositiveSmallIntegerField(verbose_name='Cholesterol Total')),
                ('triglycerids', models.BooleanField(verbose_name='Triglycerids')),
                ('tg_treatment', models.BooleanField(verbose_name='Triglycerids Treatment')),
                ('tg_level', models.PositiveSmallIntegerField(verbose_name='Triglycerids Level')),
                ('sugar', models.BooleanField(verbose_name='Sugar')),
                ('sugar_treatment', models.BooleanField(verbose_name='Sugar Treatment')),
                ('sugar_level', models.PositiveSmallIntegerField(verbose_name='Sugar Level')),
                ('surgeries', models.CharField(max_length=255, verbose_name='History of surgeries')),
                ('anxiety', models.BooleanField(verbose_name='Anxiety')),
                ('anxiety_treatment', models.BooleanField(verbose_name='Anxiety Treatment')),
                ('depression', models.BooleanField(verbose_name='Depression')),
                ('depression_treatment', models.BooleanField(verbose_name='Depression Treatment')),
                ('constipation', models.BooleanField(verbose_name='Constipation')),
                ('constipation_treatment', models.BooleanField(verbose_name='Constipation Treatment')),
                ('thyroidism', models.CharField(choices=[('I', 'Hipothyroidims'), ('Y', 'Hyperthyroidims'), ('A', 'Hipo or Hyper'), ('N', 'None')], max_length=25, verbose_name='Thyroidism')),
                ('thyroid_treatment', models.BooleanField(verbose_name='Thyroid Treatment')),
                ('food_alergies', models.CharField(max_length=255, verbose_name='Food Alergies')),
                ('sleep_habits', models.CharField(max_length=255, verbose_name='Sleep Habits')),
                ('sleep_treatment', models.BooleanField(verbose_name='Sleep Treatment')),
            ],
        ),
    ]
