# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiochemAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of analysis')),
                ('hdl', models.PositiveSmallIntegerField(verbose_name='Cholesterol HDL')),
                ('ldl', models.PositiveSmallIntegerField(verbose_name='Cholesterol LDL')),
                ('cholesterol_total', models.PositiveSmallIntegerField(verbose_name='Cholesterol Total')),
                ('tg_level', models.PositiveSmallIntegerField(verbose_name='Triglycerids Level')),
                ('sugar_level', models.PositiveSmallIntegerField(verbose_name='Sugar Level')),
                ('uric_acid', models.FloatField(verbose_name='Uric Acid')),
                ('iron', models.FloatField(verbose_name='Iron')),
                ('calcium', models.FloatField(verbose_name='Calcium')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biochem_analysis', to='patients.Patient', verbose_name='Patient')),
            ],
        ),
    ]
