# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_biochemanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of report')),
                ('left_arm_high', models.FloatField(verbose_name='Left Arm High')),
                ('left_arm_low', models.FloatField(verbose_name='Left Arm Low')),
                ('right_arm_high', models.FloatField(verbose_name='Right Arm High')),
                ('right_arm_low', models.FloatField(verbose_name='Right Arm Low')),
                ('mean_high', models.FloatField(verbose_name='Mean High')),
                ('mean_low', models.FloatField(verbose_name='Mean Low')),
                ('heart_rate', models.PositiveSmallIntegerField(verbose_name='Heart Rate')),
                ('treatment', models.BooleanField(verbose_name='In Treatment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure_report', to='patients.Patient', verbose_name='Patient')),
            ],
        ),
    ]
