# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_bloodpressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntropometricMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of measurement')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('imc', models.FloatField(verbose_name='I.M.C.')),
                ('chest', models.FloatField(verbose_name='Perim. Chest')),
                ('min_waist', models.FloatField(verbose_name='Perim. Waist Min')),
                ('hip', models.FloatField(verbose_name='Perim. Hips')),
                ('navel', models.FloatField(verbose_name='Perim. Navel')),
                ('thigh', models.FloatField(verbose_name='Perim. Thighs')),
                ('lost_weight', models.FloatField(verbose_name='Lost weight')),
                ('lost_weight_total', models.FloatField(verbose_name='Lost weight total')),
                ('lost_cm', models.FloatField(verbose_name='Lost cm')),
                ('lost_cm_total', models.FloatField(verbose_name='Lost cm total')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='patients.Patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of consultation')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('visit_number', models.PositiveSmallIntegerField(verbose_name='Visit Number')),
                ('lost_weight', models.FloatField(verbose_name='Lost Weight')),
                ('imc_reduction', models.FloatField(verbose_name='I.M.C. reduction')),
                ('pc_reduction', models.FloatField(verbose_name='P.C. reduction')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='patients.Patient', verbose_name='Patient')),
            ],
        ),
    ]
