# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_antropometricmeasurement_consultationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationdata',
            name='date',
        ),
        migrations.AlterField(
            model_name='antropometricmeasurement',
            name='lost_cm',
            field=models.FloatField(verbose_name='Lost cm (waist)'),
        ),
        migrations.AlterField(
            model_name='antropometricmeasurement',
            name='lost_cm_total',
            field=models.FloatField(verbose_name='Lost cm total (waist)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='eats_where',
            field=models.CharField(choices=[('H', 'At Home'), ('W', 'At Work'), ('S', 'In the Street'), ('F', 'In Family Home'), ('O', 'Other')], max_length=25, verbose_name='Where has meals'),
        ),
    ]
